# --- build stage ---
FROM golang:1.26-alpine AS builder

WORKDIR /app
COPY go.mod ./
RUN go mod download 2>/dev/null || true
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /order-service .

# --- runtime stage ---
FROM alpine:3.24
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /order-service .

EXPOSE 8080
ENTRYPOINT [ "/app/order-service" ]